name: Manually Deploy to Heroku with environment setup

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build the packages
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: use node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install packages
        run: npm install
      - name: build app
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: npm-packages
          path: dist/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist/
  deploy:
    name: deploy to heroku
    needs: [build]
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: npm-packages
          path: dist/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist/
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}